### ISSUE TITLE
Question: Server-side authentication

### ISSUE THREAD

**Issue by malonehedges** [alidcastano/rogue#29]
Hi there,

I was wondering if it would be possible to have a route protected by some server-side authentication.

Simplest example:
* Auth page (public)
* Secret page (loaded only if authenticated)

Most importantly, the data (including layout / content of the page) cannot be transmitted unless the client has successfully authenticated. I was hoping to use `import` and have the server only return the component if the user is authenticated but don't know how to hook into this tool (or if it is possible).

Thanks in advance!

**Comment by alidcastano** [comment]
Yes, here's how I handle this (going to mainly copy and paste some code I'm using)

I create a `Router` component with all my routes and a `getInitialProps` method that refreshes the session (the example below uses apollo)

```
const routable = (Layout, Page) => props => <Layout {...props}><Page {...props} /></Layout>

export default class Router extends React.Component {
  static async getInitialProps (ctx) {
    await Router.refreshSession(ctx)
  }

  static async refreshSession (ctx) {
    const token = getTokenFromReq(ctx.req)
    if (!ctx.store.getState().session.user && token) {
      try {
        const res = await ctx.apollo.query({ query: authUserQuery })
        ctx.store.dispatch(setSession({ user: res.data.authUser }))
      } catch (err) { // invalid or expired token 
        ctx.apollo.resetStore()
        ctx.store.dispatch(removeSession())
      }
    }
  }

  render () {
    return (
      <Switch>
        <Route exact path="/welcome" render={routable(Landing, Welcome)} />
        <Route exact path="/register" render={routable(Auth, Register)} />
        <Route exact path="/login" render={routable(Auth, Login)} />
        <Route path="/" render={routable(App, Dashboard)} />
      </Switch>
    )
  }
}
```

Then I create some middleware for handling authentication

```
const isSessionUser = (ctx) => ctx.store.getState().session.user

export const loggedInOrRedirect = (ctx) => {
  if (!isSessionUser(ctx)) {
    ctx.redirect('/welcome')
  }
}

export const loggedOutOrRedirect = (ctx) => {
  if (isSessionUser(ctx)) {
    ctx.redirect('/')
  }
}

```

and I use this middleware inside my `AppLayout` and `AuthLayout` etc. `getInitialProps` method

```
export default class AuthLayout extends React.Component {
  static async getInitialProps (ctx) {
    await loggedOutOrRedirect(ctx)
  }
}
```

Your `Router` will be the top most component and be called first, so session will be refreshed prior to running middleware inside Layout/Page to check whether user is authenticated

I plan on adding an example of this, and maybe even including this by default in starter template since everyone needs authentication for an app

But I hope it helps for now! Closing this

**Comment by malonehedges** [comment]
Thanks so much for the quick reply! I'll try this out.
