### ISSUE TITLE
What's the best way to integrate this with an existing project?

### ISSUE THREAD

**Issue by denny64** [alidcastano/rogue#32]

**Comment by alidcastano** [comment]
Depends on the existing framework and build setup

Though I wouldn't recommend trying to do that with rogue just yet

specially since your project likely uses Webpack and Parcel still has some kinks to work out (see #11)

Though the goal is that since all you'd need is an App.js, it would be trivial to convert a regular react application to rogue assuming your build setup isn't too complicated 

anyway, closing this since it's not an issue. But feel free to comment if you still have questions & I'll try to answer
